## PAIR PROGRAMMING PANDAS VII
---

In [20]:
import pandas as pd
import numpy as np
import re
import random

**EJERCICIO 1**

Cread una columna nueva y una funciÃ³n que nos de el mes en el que ocurriÃ³ el ataque. Tened en cuenta que no todas las filas tienen la misma estructura y que puede que no haya la informaciÃ³n de mes. En ese caso devolved un nulo (NaN).
ðŸ’¡ Pista ðŸ’¡PodÃ©is usar regex.

In [21]:
df = pd.read_csv('attacks5.csv')
df.head(5)

,Unnamed: 0,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,href,fatal_(y/n),injury,date
0,0,1800.00.00,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,F,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, all onboard were killed by sharks",1800
1,1,1797.05.28.R,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,FATAL,Reported May-28-1797
2,2,1792.09.12,1792.0,Provoked,ENGLAND,NaN,On the Thames River,Fishing,male,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, PROVOKED INCIDENT",12-Sep-1792
3,3,1791.00.00,1791.0,Unprovoked,AUSTRALIA,New South Wales,Port Jackson,NaN,"female, an Australian aboriginal",F,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, ""bitten in two""",1791
4,4,1788.05.10,1788.0,Boat,AUSTRALIA,New South Wales,Sydney Harbor,Fishing,boat,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury to occupants, shark bit oar and rudder",10-May-1788

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1672 entries, 0 to 1671
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1672 non-null   int64
 1   case_number  1672 non-null   object
 2   year         1672 non-null   float64
 3   type         1672 non-null   object
 4   country      1662 non-null   object
 5   area         1626 non-null   object
 6   location     1621 non-null   object
 7   activity     1641 non-null   object
 8   name         1663 non-null   object
 9   sex_         1658 non-null   object
 10  age          1518 non-null   object
 11  time         1512 non-null   object
 12  species_     1546 non-null   object
 13  href         1672 non-null   object
 14  fatal_(y/n)  1585 non-null   object
 15  injury       1664 non-null   object
 16  date         1672 non-null   object
dtypes: float64(1), int64(1), object(15)
memory usage: 222.2+ KB

In [23]:
df["date"].unique()

array(['1800', 'Reported May-28-1797', '12-Sep-1792', ..., '02-Mar-1892',
       '25-Nov-1880', '13-May-1868'], dtype=object)

In [24]:
#patron = '\w+\-'

#patron = '^\w{3}$-'

patron = '\w{3}\-'

In [25]:
# iteramos por cada fila de nuestra columna "date" para sacar los meses con el patrÃ³n previamente esstablecido

In [26]:
# Creamos una funciÃ³n, metemos el patron dentro de la funciÃ³n (variable local)

def sacar_mes(col1):
    patron = '\w{3}\-'
    try:
        mes = re.findall(patron, col1)[0]
        return mes.replace("-"," ")
    except: 
        return np.nan

In [27]:
# Hacer un apply con la funciÃ³n y crear la columna para aÃ±adir el dato
df["mes_ataque"]= df["date"].apply(sacar_mes)
df.sample(10)

,Unnamed: 0,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,href,fatal_(y/n),injury,date,mes_ataque
751,581,2005.04.16.a,2005.0,Unprovoked,AUSTRALIA,New South Wales,Bronte Beach,Surfing,Simon Letch,M,40,06h10,Bronze whaler shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury, board bitten",16-Apr-2005,Apr
1477,1307,1961.12.27,1961.0,Provoked,AUSTRALIA,Western Australia,North of main swimming area in Waterman's Bay ...,Spearfishing,John Parker,M,23,07h00,"Grey nurse shark, 2.4 m [8']",http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury, Parker shot the shark when it came ...",27-Dec-1961,Dec
1309,1139,1976.08.24,1976.0,Unprovoked,USA,Oregon,Winchester Bay,Surfing,Mike Shook,M,19,14h00,"White shark, 4.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury, board bitten",24-Aug-1976,Aug
1284,1114,1980.07.23,1980.0,Unprovoked,USA,Delaware,Dewey Beach,Standing,Phyllis Riley,F,22,Afternoon,4' to 8' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury, shark bit her bathing suit",23-Jul-1980,Jul
170,0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,Jun
825,655,2003.04.21.a,2003.0,Unprovoked,USA,Florida,"Shepard Park, Cocoa Beach, Brevard County",Surfing,male,M,17,13h30,Unidentified species,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Survived,21-Apr-2003,Apr
408,238,2012.12.05,2012.0,Unprovoked,USA,Hawaii,Kauai,Surfing,"""Lorrin""",M,60,13h20,10' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Lacerations to left foot,05-Dec-2012,Dec
222,52,2016.11.14,2016.0,Unprovoked,USA,Hawaii,"Kamaole Beach Park I, Maui",Floating,Barbara Zawacki,F,58,10h30,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Injuries to right calf and thigh,14-Nov-2016,Nov
433,263,2012.06.15,2012.0,Provoked,USA,Florida,"Summerland Key, Monroe County",Fishing,male,M,23,14h20,Nurse shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Superficial injury to calf by hooked shark PRO...,15-Jun-2012,Jun
584,414,2008.08.30.b,2008.0,Invalid,USA,Hawaii,"McKenzie Beach Park in Pahoa, Hawai'i",Swimming,Kameron Brown,M,27,19h20,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,Death was probably due to drowning,30-Aug-2008,Aug

---

**EJERCICIO 2**

Vamos con la columna fatal_(y/n). Lo primero que tenÃ©is que hacer es evaluar los valores Ãºnicos que hay. EsperarÃ­amos tener solo dos valores: y y n, pero tristemente no serÃ¡ asÃ­ ðŸ˜­. Cread una columna nueva y una funciÃ³n que devuelva Ãºnicamente y o n y que devuelva un nulo (NaN) si no se encuentra el valor.

In [28]:
#Hacemos un unique para ver los valores de la columna. No estÃ¡ limpia, deberemos limpiar estos datoss para que nos sean de utilidad 
df["fatal_(y/n)"].unique()

array(['Y', 'N', nan, 'UNKNOWN', 'M', '2017', ' N'], dtype=object)

In [29]:
# definimos una funcion para separar los valores vÃ¡lidos. Como hemos observado con el unique() tenemos un ' N'. por ello, haremos una condicion aplicando strip para eliminar el espacio y que este valor nos sea vÃ¡lido
def limpiar (col):
   if col == "N":
      return col 
   if col == "Y":
      return col
   if col == " N":
    return col.strip()
   else:
        return np.nan

In [30]:
limpiar("fatal_(y/n)")

nan

In [31]:
df["fatal"]= df["fatal_(y/n)"].apply(limpiar)
df.head()

,Unnamed: 0,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,href,fatal_(y/n),injury,date,mes_ataque,fatal
0,0,1800.00.00,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,F,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, all onboard were killed by sharks",1800,NaN,Y
1,1,1797.05.28.R,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,FATAL,Reported May-28-1797,May,Y
2,2,1792.09.12,1792.0,Provoked,ENGLAND,NaN,On the Thames River,Fishing,male,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, PROVOKED INCIDENT",12-Sep-1792,Sep,Y
3,3,1791.00.00,1791.0,Unprovoked,AUSTRALIA,New South Wales,Port Jackson,NaN,"female, an Australian aboriginal",F,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, ""bitten in two""",1791,NaN,Y
4,4,1788.05.10,1788.0,Boat,AUSTRALIA,New South Wales,Sydney Harbor,Fishing,boat,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury to occupants, shark bit oar and rudder",10-May-1788,May,N

---

**EJERCICIO 3**

Seguid la misma lÃ³gica que en el ejercicio anterior pero con la columna sex. Pero en este caso vamos a incluir un retito mÃ¡s: En este caso querremos tener dos valores Ãºnicos F y M. De nuevo en la columna hay otros carÃ¡cteres raros como 'M ', 'lli', 'N', '.'. En esos casos, queremos que se reemplacen por M o F de forma aleatoria (tendrÃ©is que usar la librerÃ­a random). BONUS: En caso de que sea nulo, que la funciÃ³n devuelva nulo (np.nan).

In [32]:
#veamos que valores tenemos en la columna sex_
df["sex_"].unique()

array(['F', nan, 'M', 'lli'], dtype=object)

In [33]:
#hagamos una funciÃ³n para que 'lli' se convierta en F/M de manera aleatoria, para ello hemos recurrido a google y encontrado un nuevo mÃ©todo de Random, random.choice()
#primero crearemos una lista con nuestras opciones para pasarsela a este mÃ©todo y que el decida cual poner.

def sustituir_aleatorio (col):
    sexos = ["F","M"]
    if col == "F":
        return col
    elif col == "M":
        return col
    elif col == "lli":
       col = (np.random.choice(sexos))
       return col

In [34]:
sustituir_aleatorio(["sex_"])

In [35]:
df["sexo"]= df["sex_"].apply(sustituir_aleatorio)
df["sexo"].unique()

array(['F', None, 'M'], dtype=object)

In [36]:
df.sample(20)

,Unnamed: 0,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,href,fatal_(y/n),injury,date,mes_ataque,fatal,sexo
188,18,2017.11.24,2017.0,Unprovoked,USA,California,"Stillwater Cove, Monterey County",Spearfishing,Grigor Azatian,M,25,13h45,"White shark, 4.6 m",http://sharkattackfile.net/spreadsheets/pdf_di...,N,Right leg bitten,24-Nov-2017,Nov,N,M
486,316,2011.04.16,2011.0,Unprovoked,NEW ZEALAND,South Island,Snapper Point,Surfing,Laine Hobson,M,41,Afternoon,possibly a bronze whaler shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Puncture to left hand,16-Apr-2011,Apr,N,M
1312,1142,1975.11.19.a,1975.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,"South Beach, Durban",Standing,Michael van den Berg,M,33,10h00,Juvenile dusky shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Left foot lacerated,19-Nov-1975,Nov,N,M
547,377,2009.08.01,2009.0,Unprovoked,USA,Louisiana,"Curlew Island, Breton Sound",Wade Fishing,"Chris Haynes, Jr.",M,56,10h00,Bull shark?,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Right ankle & foot bitten,01-Aug-2009,Aug,N,M
1081,911,1994.01.03,1994.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Hibberdene,Swimming,Ian Galbraith,M,33,16h15,"1.3 m [4'3""] shark",http://sharkattackfile.net/spreadsheets/pdf_di...,N,Foot bitten,03-Jan-1994,Jan,N,M
1156,986,1989.10.22,1989.0,Unprovoked,AUSTRALIA,Tasmania,Shelly Point,Surfing,Steven Jillet,M,17,14h20,2.7 m [9'] white shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury, board bitten",22-Oct-1989,Oct,N,M
915,745,2001.04.12.b,2001.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,"John Fasio, Jr",M,12,12h34,Possibly a juvenile blacktip or spinner shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Foot & ankle lacerated,12-Apr-2001,Apr,N,M
166,166,ND.0004,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,FATAL,Before 1903,NaN,Y,M
1408,1238,1965.02.04,1965.0,Unprovoked,USA,Massachusetts,"Granite Pier, Rockport",Scuba diving,Ronald R. Powell,M,18,14h30,1.2 m [4'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Punctures on left thigh,04-Feb-1965,Feb,N,M
1406,1236,1965.03.14,1965.0,Unprovoked,USA,Florida,"Pompano Beach, Palm Beach County",Free diving,Rick MacNeilly,M,16,13h30,Mako shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Survived,14-Mar-1965,Mar,N,M
1593,1423,1947.04.20,1947.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,"Country Club Beach, Durban",Treading water,"Aubrey ""Bill"" Nielsen",M,21,12h00,"1.5 m, 45-kg shark",http://sharkattackfile.net/spreadsheets/pdf_di...,N,Ankle & shin lacerated,20-Apr-1947,Apr,N,M
1623,1453,1937.05.15,1937.0,Unprovoked,AUSTRALIA,Queensland,"Ross River, Townsville","Refused permission to cross on the ferry, he w...",William Tennant,M,33,Night,2 days later a 600-lb shark was caught 100 yar...,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, left arm severed at elbow, right arm bi...",15-May-1937,May,Y,M
1477,1307,1961.12.27,1961.0,Provoked,AUSTRALIA,Western Australia,North of main swimming area in Waterman's Bay ...,Spearfishing,John Parker,M,23,07h00,"Grey nurse shark, 2.4 m [8']",http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury, Parker shot the shark when it came ...",27-Dec-1961,Dec,N,M
1462,1292,1962.06.04,1962.0,Provoked,USA,California,"12' tank at Steinhart Aquarium, San Francisco","Scuba diving, attempting to catch a captive shark","Norval J. ""Tom"" Green",M,55,13h30,"Sevengill shark, 1.2 m [4']",http://sharkattackfile.net/spreadsheets/pdf_di...,N,Right forearm bitten PROVOKED INCIDENT,04-Jun-1962,Jun,N,M
1411,1241,1964.12.09,1964.0,Unprovoked,PAPUA NEW GUINEA,Bougainville (North Solomons),"Off Sing Village, Buka Island","Canoe swamped, swimming back to canoe","Soso, a male",M,28,Late afternoon,2.1 m [7'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Survived,09-Dec-1964,Dec,N,M
522,352,2010.04.19,2010.0,Unprovoked,USA,Hawaii,"Hanalei Bay, Kauai",Surfing,Jim Rawlinson,M,68,16h00,14' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,"No injury, surfboard bitten",19-Apr-2010,Apr,N,M
1468,1298,1962.01.18,1962.0,Invalid,SOUTH AFRICA,KwaZulu-Natal,Margate,"Fishing, slipped on rocks & fell into sea",Jacobus Vermaak,M,40,13h10,Shark involvement prior to death was not confi...,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,Possible drowning / post mortem scavenging by ...,18-Jan-1962,Jan,NaN,M
1014,844,1997.06.15,1997.0,Unprovoked,FIJI,Taveuni,Off a small island 5 km from Garden Island Resort,Snorkeling,Liz Rogers,F,47,14h30,"Tiger shark, 2.7m [9']",http://sharkattackfile.net/spreadsheets/pdf_di...,N,"Bitten on inner thigh, leg surgically amputated",15-Jun-1997,Jun,N,F
1644,1474,1929.01.12,1929.0,Unprovoked,AUSTRALIA,New South Wales,Bondi,Body surfing,Colin James Stewart,M,14,18h10,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, right thigh & hip bitten",12-Jan-1929,Jan,Y,M
408,238,2012.12.05,2012.0,Unprovoked,USA,Hawaii,Kauai,Surfing,"""Lorrin""",M,60,13h20,10' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Lacerations to left foot,05-Dec-2012,Dec,N,M

---

**EJERCICIO 4**

Una vez que hayÃ¡is terminado eliminad las columnas originales conservando las nuevas.

In [37]:
df.columns

Index(['Unnamed: 0', 'case_number', 'year', 'type', 'country', 'area',
       'location', 'activity', 'name', 'sex_', 'age', 'time', 'species_',
       'href', 'fatal_(y/n)', 'injury', 'date', 'mes_ataque', 'fatal', 'sexo'],
      dtype='object')

In [38]:
df.drop(['fatal_(y/n)','sex_' ], axis = 1)

,Unnamed: 0,case_number,year,type,country,area,location,activity,name,age,time,species_,href,injury,date,mes_ataque,fatal,sexo
0,0,1800.00.00,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"FATAL, all onboard were killed by sharks",1800,NaN,Y,F
1,1,1797.05.28.R,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,FATAL,Reported May-28-1797,May,Y,None
2,2,1792.09.12,1792.0,Provoked,ENGLAND,NaN,On the Thames River,Fishing,male,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"FATAL, PROVOKED INCIDENT",12-Sep-1792,Sep,Y,M
3,3,1791.00.00,1791.0,Unprovoked,AUSTRALIA,New South Wales,Port Jackson,NaN,"female, an Australian aboriginal",NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"FATAL, ""bitten in two""",1791,NaN,Y,F
4,4,1788.05.10,1788.0,Boat,AUSTRALIA,New South Wales,Sydney Harbor,Fishing,boat,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"No injury to occupants, shark bit oar and rudder",10-May-1788,May,N,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1667,1497,1901.07.30,1901.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Windmill Beach,Swimming,"John Hendrick Adrian Chandler, a prisoner of war",29,14h15,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,"Right leg bitten & foot severed, right arm bit...",30-Jul-1901,Jul,Y,M
1668,1498,1894.11.28,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,"""Lost his arm""",28-Nov-1894,Nov,N,M
1669,1499,1892.03.02,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,Lacerations to calf by netted shark PROVOKED I...,02-Mar-1892,Mar,N,M
1670,1500,1880.11.25,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...,"Feet bitten, surgically amputated FATAL",25-Nov-1880,Nov,Y,M
1671,1501,1868.05.13,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,35,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,http://sharkattackfile.net/spreadsheets/pdf_di...,"FATAL, upper left thigh, groin & buttocks seve...",13-May-1868,May,Y,M

---

**EJERCICIO 5**

Guardad el dataframe en un csv que usaremos mÃ¡s adelante

In [40]:
df.to_csv("attacks6.csv")